#!/bin/bash

## 1. Configuraciones previas

# Inicializar temporizador de tiempo de ejecución
start=$(date +%s)

# Establecer directorios de salida
INPUT_DIR=$1 # Carpeta que contiene los resultados de fastp
GENOME_DIR=$2 # Carpeta que contiene el índice del genoma

# Crear directorio de salida
OUTPUT_DIR="aligned_reads"
mkdir -p $OUTPUT_DIR

## 2. Alinear cada muestra al genoma de referencia

# Ejecutar hisat2 para cada muestra
for R1 in "$INPUT_DIR"/*_1.fastq.gz
do
	sample=$(basename "$R1" _1.fastq.gz)
	R2="$INPUT_DIR/${sample}_2.fastq.gz"

	hisat2 -x $GENOME_DIR/GRCh38_index \
	-1 $R1 \
	-2 $R2 \
	-S "${OUTPUT_DIR}/${sample}.sam" \
	-p 4

	echo "${sample} sample correctly aligned with reference genome"

	# Convertir de SAM a BAM y ordenar
	samtools view -@ 8 -bS "$OUTPUT_DIR/${sample}.sam" | samtools sort -@ 8 -o "$OUTPUT_DIR/${sample}sorted.bam"
	samtools index "$OUTPUT_DIR/${sample}sorted.bam"
	rm "$OUTPUT_DIR/${sample}.sam"

	echo "${sample}sorted.bam correctly generated"
done

## 3. Ajustes finales

# Mostrar tiempo de ejecución
end=$(date +%s)
echo "Time used: $(echo "scale=2; ($end - $start)/60" | bc) minutes"
