#!/bin/bash

## 1. Configuraciones previas

# Inicializar temporizador de tiempo de ejecución
start=$(date +%s)

# Directorio con los datos RNA-seq crudos
INPUT_DIR=$1

# Crear directorio de salida
OUT_DIR="fastp_out"
mkdir -p "$OUT_DIR"

## 2. Control de calidad con fastp

# Ejecutar fastp
for R1 in "$INPUT_DIR"/*_1*
do
	sample=$(basename "$R1" _1.fastq.gz)
	R2="$INPUT_DIR/${sample}_2.fastq.gz"

	fastp -i "$R1" -I "$R2" \
    	-o "${OUT_DIR}/${sample}_1.fastq.gz" -O "${OUT_DIR}/${sample}_2.fastq.gz" \
	-q 5 -u 50 \
	--n_base_limit 10 \
      	--adapter_fasta adapters.fa \
	--thread 14 \
	--html "${OUT_DIR}/html_${sample}.html" \
	--json "${OUT_DIR}/json_${sample}.json"
done

# Mostrar tiempo de ejecución
end=$(date +%s)
echo "Time used: $(echo "scale=2; ($end - $start)/60" | bc) minutes"
